# Add configuration values here, as shown below.
pusher_app_id: "2954"
pusher_key: 7381a978f7dd7f9a1117
pusher_secret: abdc3b896a0ffb85d373
stripe_api_key: sk_test_GCj1bV5HAsKrZhqU9gyvUgh5
stripe_publishable_key: pk_test_tr9lJQPRZfkhr7HLirx8MYvS

production:
  stripe_api_key: sk_live_dMYPHsCz7jyEYtmS7Z4Cq4Vi
  stripe_publishable_key: pk_live_knklkmzpNacKBWTLJQpT7B3z

SENDGRID_USERNAME: app66004946@heroku.com
SENDGRID_PASSWORD: w2ifcmdr1492
